### ISSUE TITLE
qgis_basemaps.py support pls?

### ISSUE THREAD

**Issue by Strangehill** [klakar/QGIS_resources#1]
Tried to run qgis_basemaps.py per "QGIS for Absolute Beginners" but met this error. 
any tips?
thx

```
>>> exec(open('/Users/coda/QGIS/qgis_basemaps.py'.encode('utf-8')).read())
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 5296: ordinal not in range(128)
```

**Comment by klakar** [comment]
To run the script you can also open the qgis_basemaps.py file in a text editor, copy all the code, and paste it at the Python prompt in QGIS. You may need to effectuate the last line in the script manually when everything else is run by pressing enter.

**Comment by Strangehill** [comment]
That worked perfectly. Thanks for the clarity in the instructions.
