### ISSUE TITLE
Unkown file style version

### ISSUE THREAD

**Issue by patnik** [klakar/QGIS_resources#4]
Hi, 
when I am trying to upload the xml file, I am getting this error "Unkown file style version: 2". Any idea where this might come from? I am using the QGIS version 3.10.7.

Thanks

**Comment by klakar** [comment]
Which file?

**Comment by patnik** [comment]
I have tried with a few. For example bloated.xml
I think the error refers to the second line: qgis_style version="2". Any ideas?

**Comment by klakar** [comment]
Actually I have no idea. The styles are exported from 3.14 and as a default they all have the version set to 2.
One possibility is that I've used some features only available in versions after 3.10, and that 3.10 only can handle style versions prior to 2.
If you try to export a style of your own, what version do you have in your file?

**Comment by patnik** [comment]
When I export a style it says version:1. 
So this may be the case. 
Thanks!
