### ISSUE TITLE
measure_construction

### ISSUE THREAD

**Issue by pablomandolesi** [klakar/QGIS_resources#5]
hi kurt, i was able to import the measure_construction style, but i can`t get it to show the measures. I know this isn`t an issue, but i was wondering if you could help me. Do i have to create a field for calculating the measures? or does the style do it by it`s own? Or is it a projection thing? Thanks!!!
![error](https://user-images.githubusercontent.com/1580000/89045711-595f7b80-d322-11ea-8332-8844a70df92f.png)

**Comment by klakar** [comment]
Your data layer must be in a projected CRS. Coordinates need to be in either meters or feet.
Since the labels only will show wrong values for layers in any other projection the labels are filtered out, unless the coordinate unit as mentioned is meters or feet.
